version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - cd /root
      - mkdir -p mxnet/python pillow/python keras/python scipy/python gluoncv/python gluonnlp/python xgboost/python sklearn/python numpy/python
      - python3 -m pip install --user pip --upgrade
      - python3 -m pip install --user virtualenv
      - python3 -m virtualenv MXNet
      - source MXNet/bin/activate
      - pip install numpy scikit-learn==0.24.1 six==1.12.0 cycler==0.10.0 kiwisolver==1.1.0 pyparsing==2.4.0
      - rm -rf $(find MXNet/lib/python3.7/site-packages/numpy -name tests)
      - rm -rf $(find MXNet/lib/python3.7/site-packages/ -name tests)
      - cp -r MXNet/lib/python3.7/site-packages/six* sklearn/python
      - cp -r MXNet/lib/python3.7/site-packages/pyparsing* sklearn/python
      - cp -r MXNet/lib/python3.7/site-packages/kiwisolver* sklearn/python
      - cp -r MXNet/lib/python3.7/site-packages/cycler* sklearn/python
      - cp -r MXNet/lib/python3.7/site-packages/six* sklearn/python
      - cp -r MXNet/lib/python3.7/site-packages/* sklearn/python
      - cp -r MXNet/lib/python3.7/site-packages/sklearn* sklearn/python
      - cp -r MXNet/lib/python3.7/site-packages/numpy* sklearn/python
      - rm -rf sklearn/python/pip*
      - rm -rf sklearn/python/wheel*
      - rm -rf sklearn/python/setuptools*
      - rm -rf sklearn/python/pkg_resources
artifacts:
  name: sklearn
  base-directory: /root/sklearn
  files:
    - '**/*'
  discard-paths: no
  secondary-artifacts:
    keras:
      base-directory: /root/keras
      files:
        - '**/*'
      discard-paths: no
    pillow:
      base-directory: /root/pillow
      files:
        - '**/*'
      discard-paths: no
    scipy:
      base-directory: /root/scipy
      files:
        - '**/*'
      discard-paths: no
    gluonnlp:
      base-directory: /root/gluonnlp
      files:
        - '**/*'
      discard-paths: no
    gluoncv:
      base-directory: /root/gluoncv
      files:
        - '**/*'
      discard-paths: no
    mxnet:
      base-directory: /root/mxnet
      files:
        - '**/*'
      discard-paths: no
